{% set name = "roman-numerals" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/roman_numerals-{{ version }}.tar.gz
  sha256: 1af8b147eb1405d5839e78aeb93131690495fe9da5c91856cb33ad55a7f1e5b2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.7,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - roman_numerals
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/AA-Turner/roman-numerals
  summary: Manipulate well-formed Roman numerals
  license: 0BSD OR CC0-1.0
  license_file: LICENCE.rst

extra:
  recipe-maintainers:
    - AA-Turner
    - ocefpaf
